apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "todolist.fullname" . }}
  labels:
    app: {{ template "todolist.name" . }}
    chart: {{ template "todolist.chart" . }}
    release: "{{ .Release.Name }}"
    harness.io/release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "todolist.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "todolist.name" . }}
        release: {{ .Release.Name }}
        harness.io/release: {{ .Release.Name }}
    spec:
      {{- if .Values.dockercfg}}
      imagePullSecrets:
      - name: {{.Values.name}}-dockercfg
      {{- end}}
      containers:
        - name: {{ .Chart.Name }}
          image: {{.Values.image}}
          imagePullPolicy: {{ .Values.pullPolicy }}
          {{- if or .Values.env.config .Values.env.secrets}}
          envFrom:
          {{- if .Values.env.config}}
          - configMapRef:
              name: {{.Values.name}}
          {{- end}}
          {{- if .Values.env.secrets}}
          - secretRef:
              name: {{.Values.name}}
          {{- end}}
          {{- end}}
