apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deploy
  namespace: default
spec:
  template :
    spec:
      containers:
        - name: example-app
          image: <+secrets.getValue("image")>

---
apiVersion: v1
kind: Service
metadata:
  name: example-service
  namespace: default
spec:
  selector:
    app: <+secrets.getValue("appName")>
