apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deploy
  namespace: default
spec:
  template :
    spec:
      containers:
        - name: example-app
          image: <+pipeline.variables.imageName>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deploy
spec:
  replicas: <+pipeline.variables.replicaPL>
