apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-deployment
  namespace: default
spec:
  template :
    spec:
      containers:
        - name: the-container
          image: ${artifact.metadata.image}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-deployment
  namespace: default
spec:
  replicas: ${serviceVariable.replica}
