harnessApiVersion: '1.0'
type: GIT
branch: main
disableUserGitConfig: false
keyAuth: false
password: gcpkms:pratyush git pass
providerType: GIT
url: https://github.com/GoelPratyush99/PipelineNgAutomation.git
urlType: REPO
username: git
