apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Values.gitSecret}}
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command:
          - sleep
          - "3600"
      - name: {{.Values.gitSecret}}
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4
