resources:
  - ../../../application
namePrefix: prod-
configMapGenerator:
- name: example-config
  namespace: default

  files:
    - configs/config.json
patchesStrategicMerge:
  - env.yaml
