apiVersion: v1
kind: Service
metadata:
  name: artera
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: artera
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: artera
  name: artera
  namespace: harness-delegate-ng
spec:
  minReadySeconds: 1
  replicas: 2
  selector:
    matchLabels:
      app: artera
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: artera
    spec:
      containers:
        - image: willReplace
          name: artera
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 1000m
              memory: 3500Mi
            requests:
              cpu: 100m
