apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
      version: v1
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        version: v1
    spec:
      containers:
        - name: {{ .Values.name }}
          image: buoyantio/bb:v0.0.6
          args:
            - terminus
            - "--h1-server-port=6060"
            - "--response-text=v1"
          ports:
            - containerPort: 6060