apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-svc-v2
spec:
  selector:
    app: {{ .Values.name }}
    version: v2
  ports:
    - name: http
      port: 6060
      targetPort: 6060