apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-traffic-generator-svc
spec:
  selector:
    app: {{ .Values.name }}-traffic-generator
  ports:
    - name: metrics
      port: 9999
      targetPort: 9999