---
apiVersion: v1
data:
  otel-agent-config: |
    extensions:
      health_check:

    receivers:
      awscontainerinsightreceiver:

    processors:
      batch/metrics:
        timeout: 60s

    exporters:
      awsemf:
        namespace: ContainerInsights
        log_group_name: '/aws/containerinsights/{ClusterName}/performance'
        log_stream_name: '{NodeName}'
        resource_to_telemetry_conversion:
          enabled: true
        dimension_rollup_option: NoDimensionRollup
        parse_json_encoded_attr_values: [Sources, kubernetes]
        metric_declarations:
          # node metrics
          - dimensions: [[NodeName, InstanceId, ClusterName]]
            metric_name_selectors:
              - node_cpu_utilization
              - node_memory_utilization
              - node_network_total_bytes
              - node_cpu_reserved_capacity
              - node_memory_reserved_capacity
              - node_number_of_running_pods
              - node_number_of_running_containers
          - dimensions: [[ClusterName]]
            metric_name_selectors:
              - node_cpu_utilization
              - node_memory_utilization
              - node_network_total_bytes
              - node_cpu_reserved_capacity
              - node_memory_reserved_capacity
              - node_number_of_running_pods
              - node_number_of_running_containers
              - node_cpu_usage_total
              - node_cpu_limit
              - node_memory_working_set
              - node_memory_limit

          # pod metrics
          - dimensions: [[PodName, Namespace, ClusterName], [Service, Namespace, ClusterName], [Namespace, ClusterName], [ClusterName]]
            metric_name_selectors:
              - pod_cpu_utilization
              - pod_memory_utilization
              - pod_network_rx_bytes
              - pod_network_tx_bytes
              - pod_cpu_utilization_over_pod_limit
              - pod_memory_utilization_over_pod_limit
          - dimensions: [[PodName, Namespace, ClusterName], [ClusterName]]
            metric_name_selectors:
              - pod_cpu_reserved_capacity
              - pod_memory_reserved_capacity
          - dimensions: [[PodName, Namespace, ClusterName]]
            metric_name_selectors:
              - pod_number_of_container_restarts

          # cluster metrics
          - dimensions: [[ClusterName]]
            metric_name_selectors:
              - cluster_node_count
              - cluster_failed_node_count

          # service metrics
          - dimensions: [[Service, Namespace, ClusterName], [ClusterName]]
            metric_name_selectors:
              - service_number_of_running_pods

          # node fs metrics
          - dimensions: [[NodeName, InstanceId, ClusterName], [ClusterName]]
            metric_name_selectors:
              - node_filesystem_utilization

          # namespace metrics
          - dimensions: [[Namespace, ClusterName], [ClusterName]]
            metric_name_selectors:
              - namespace_number_of_running_pods

    service:
      pipelines:
        metrics:
          receivers: [awscontainerinsightreceiver]
          processors: [batch/metrics]
          exporters: [awsemf]

      extensions: [health_check]
kind: ConfigMap
metadata:
  labels:
    app: opentelemetry
    app.kubernetes.io/environment: nonproduction
    app.kubernetes.io/instance: opentelemetry
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: opentelemetry
    app.kubernetes.io/owner: fire-team
    component: otel-agent-conf
  name: otel-agent-conf
  namespace: inst-system
---
apiVersion: v1
imagePullSecrets:
  - name: dockerhub-image-pull-secret
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/environment: nonproduction
    app.kubernetes.io/instance: opentelemetry
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: opentelemetry
    app.kubernetes.io/owner: fire-team
  name: aws-otel-sa
  namespace: inst-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/environment: nonproduction
    app.kubernetes.io/instance: opentelemetry
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: opentelemetry
    app.kubernetes.io/owner: fire-team
  name: aoc-agent-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - nodes
      - endpoints
    verbs:
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - replicasets
    verbs:
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes/proxy
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - nodes/stats
      - configmaps
      - events
    verbs:
      - create
      - get
  - apiGroups:
      - ""
    resourceNames:
      - otel-container-insight-clusterleader
    resources:
      - configmaps
    verbs:
      - get
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/environment: nonproduction
    app.kubernetes.io/instance: opentelemetry
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: opentelemetry
    app.kubernetes.io/owner: fire-team
  name: aoc-agent-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aoc-agent-role
subjects:
  - kind: ServiceAccount
    name: aws-otel-sa
    namespace: inst-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/environment: nonproduction
    app.kubernetes.io/instance: opentelemetry
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: opentelemetry
    app.kubernetes.io/owner: fire-team
  name: aws-otel-eks-ci
  namespace: inst-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/environment: nonproduction
      app.kubernetes.io/instance: opentelemetry
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/name: opentelemetry
      app.kubernetes.io/owner: fire-team
      name: aws-otel-eks-ci
  template:
    metadata:
      labels:
        app.kubernetes.io/environment: nonproduction
        app.kubernetes.io/instance: opentelemetry
        app.kubernetes.io/managed-by: kustomize
        app.kubernetes.io/name: opentelemetry
        app.kubernetes.io/owner: fire-team
        name: aws-otel-eks-ci
    spec:
      containers:
        - command:
            - /awscollector
            - --config=/conf/otel-agent-config.yaml
          env:
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: amazon/aws-otel-collector:v0.17.0
          imagePullPolicy: Always
          name: aws-otel-collector
          resources:
            limits:
              cpu: 20m
              memory: 20Mi
            requests:
              cpu: 20m
              memory: 20Mi
          volumeMounts:
            - mountPath: /rootfs
              name: rootfs
              readOnly: true
            - mountPath: /var/run/docker.sock
              name: dockersock
              readOnly: true
            - mountPath: /var/lib/docker
              name: varlibdocker
              readOnly: true
            - mountPath: /sys
              name: sys
              readOnly: true
            - mountPath: /dev/disk
              name: devdisk
              readOnly: true
            - mountPath: /conf
              name: otel-agent-config-vol
      priorityClassName: system-node-critical
      serviceAccountName: aws-otel-sa
      volumes:
        - configMap:
            items:
              - key: otel-agent-config
                path: otel-agent-config.yaml
            name: otel-agent-conf
          name: otel-agent-config-vol
        - hostPath:
            path: /
          name: rootfs
        - hostPath:
            path: /var/run/docker.sock
          name: dockersock
        - hostPath:
            path: /var/lib/docker
          name: varlibdocker
        - hostPath:
            path: /sys
          name: sys
        - hostPath:
            path: /dev/disk/
          name: devdisk
