apiVersion: v1
kind: Template
metadata:
  name: redis-template
  annotations:
    description: “Description”
    iconClass: “icon-redis”
    tags: “database,nosql”
objects:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: test-todolist-deployment3
      labels:
        app: ${REDIS_PASSWORD}
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: todolist
      template:
        metadata:
          labels:
            app: todolist
        spec:
          containers:
            - name: todolist
              image: library/nginx:mainline
              ports:
                - containerPort: 80
parameters:
  - description: Password used for Redis authentication
    from: ‘[A-Z0-9]{8}’
    generate: expression
    name: REDIS_PASSWORD
labels:
  redis: master
