
apiVersion: v1
kind: Service
metadata:
  name: harness-example-137-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: harness-example-138